paths:
  model_dataframe: "./data/processed_subset.csv"
  model_path: "./model/model.h5"
  training_history_path: "./model/training_history.csv"

model:
  input_shape: [224, 224]
  target_encoder:
    print:
      [
        "embroidered",
        "solid",
        "graphic",
        "floral",
        "striped",
        "lattice",
        "pleated",
      ]
    sleeves: ["sleeveless", "long_sleeve", "short_sleeve"]
    neckline: ["no_neckline", "v_neckline", "crew_neckline", "square_neckline"]
  target: ["print_encoded", "sleeves_encoded", "neckline_encoded"]
  paths: "processed_path"
  class_mode: "multi_output"
  freeze_convolutional_layers: False
  batch_size: 32
  random_seed: 12345
  learning_rate: 0.01
  early_stopping_patience: 10
  lr_reducer_factor: 0.1
  lr_reducer_patience: 5
  min_lr: .000001
